### PR TITLE
MakeZurich 2020 update

### PR DESCRIPTION
**Pull request by loleg**
Please comment about any issues or fixes you'd like to see happen in this deployment to prepare for the next MakeZurich!

### CODE REVIEW

**Comment by gonzalocasas** [comment]
LGTM! But I don't really know what to look for in it. Is it an update to the latest dribdat?

**Comment by loleg** [comment]
Yes, and an invitation to pile a few more commits into the fray.

**Comment by gonzalocasas** [comment]
👍 🚀

**Comment by gonzalocasas** [comment]
Should I merge or do you do it?

**Comment by loleg** [comment]
Let's merge once I have time to attend to at least @tamberg 's issue, and
when we can do some testing. The database needs to be migrated as well.

**Pull request merged**
